version: "3"
services:
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: forumpwd
      POSTGRES_USER: forumuser
      POSTGRES_DB: forum
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend/
    ports:
      - 8001:3000
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=forum
      - DB_USER=forumuser
      - DB_PASS=forumpwd
    command: npm run start:dev
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - 8000:3000
    environment:
      - REACT_APP_API_BASE=http://backend:3000
      - PORT=3000
    depends_on:
      - backend
volumes:
  dbdata:
