export enum PermissionEnum {
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  USER_PERMISSION_UPDATE = 'USER_PERMISSION_UPDATE',
  USER_ROLE_UPDATE = 'USER_ROLE_UPDATE',

  POST_READ = 'POST_READ',
  POST_CREATE = 'POST_CREATE',
  POST_UPDATE = 'POST_UPDATE',
  POST_DELETE = 'POST_DELETE',
  POST_APPROVE = 'POST_APPROVE',

  COMMENT_READ = 'COMMENT_READ',
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_UPDATE = 'COMMENT_UPDATE',
  COMMENT_DELETE = 'COMMENT_DELETE',
}
